/**
 * Regenerates the Barber Stucco brand assets from the SVG mark geometry and
 * a Great Vibes (SIL OFL 1.1) outline conversion of the wordmark.
 *
 *   node scripts/build-brand.mjs /path/to/GreatVibes-Regular.ttf
 *
 * The generated files are committed, so you only need to run this if the
 * mark or the wordmark text changes.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const TTF = process.argv[2];

const INK = "#06191B";
const TEAL = "#129AA3";
const TEAL_BRIGHT = "#1EC8D0";

/* ---------- the mark ---------------------------------------------------- */
/* A geometric facade: pitched ink silhouette, a teal arched reveal cut to the
   base, and the heart from the original mark seated in the gable.          */
const HOUSE = "M32 6 L59 27 V55 Q59 59 55 59 H9 Q5 59 5 55 V27 Z";
const ARCH = "M22 59 V44 A10 10 0 0 1 42 44 V59 Z";
const HEART =
  "M12 21 C12 21 3 14.4 3 8.5 A5.5 5.5 0 0 1 12 5 A5.5 5.5 0 0 1 21 8.5 C21 14.4 12 21 12 21 Z";
const HEART_T = "translate(23.33 13.95) scale(0.7222 0.6215)";

/* ---------- wordmark ---------------------------------------------------- */
function cmdsToD(cmds, dp = 2) {
  const n = (v) => {
    const r = Number(v.toFixed(dp));
    return Object.is(r, -0) ? 0 : r;
  };
  let out = "";
  let open = false;
  for (const c of cmds) {
    if (c.type === "M" && open) out += "Z";
    if (c.type === "M") open = true;
    if (c.type === "M") out += `M${n(c.x)} ${n(c.y)}`;
    else if (c.type === "L") out += `L${n(c.x)} ${n(c.y)}`;
    else if (c.type === "C")
      out += `C${n(c.x1)} ${n(c.y1)} ${n(c.x2)} ${n(c.y2)} ${n(c.x)} ${n(c.y)}`;
    else if (c.type === "Q") out += `Q${n(c.x1)} ${n(c.y1)} ${n(c.x)} ${n(c.y)}`;
    else if (c.type === "Z") {
      out += "Z";
      open = false;
    }
  }
  if (open) out += "Z";
  return out;
}

async function buildWordmark() {
  const opentype = (await import("opentype.js")).default;
  const font = opentype.parse(fs.readFileSync(TTF).buffer);
  const size = 200;
  const scale = size / font.unitsPerEm;
  const text = "Barber Stucco";
  let x = 0;
  let prev = null;
  const parts = [];
  const bb = { x1: Infinity, y1: Infinity, x2: -Infinity, y2: -Infinity };
  for (const ch of text) {
    const g = font.charToGlyph(ch);
    if (prev) x += (font.getKerningValue(prev, g) || 0) * scale;
    const p = g.getPath(x, 0, size);
    const b = p.getBoundingBox();
    if (ch !== " " && Number.isFinite(b.x1)) {
      bb.x1 = Math.min(bb.x1, b.x1);
      bb.y1 = Math.min(bb.y1, b.y1);
      bb.x2 = Math.max(bb.x2, b.x2);
      bb.y2 = Math.max(bb.y2, b.y2);
    }
    parts.push(cmdsToD(p.commands));
    x += g.advanceWidth * scale;
    prev = g;
  }
  return {
    d: parts.join(""),
    transform: `translate(${(-bb.x1).toFixed(2)} ${(-bb.y1).toFixed(2)})`,
    width: +(bb.x2 - bb.x1).toFixed(2),
    height: +(bb.y2 - bb.y1).toFixed(2),
  };
}

/* ---------- emit -------------------------------------------------------- */
const markGroup = (ink, teal, extra = "") => `  <g${extra}>
    <path d="${HOUSE}" fill="${ink}"/>
    <path d="${ARCH}" fill="${teal}"/>
    <g transform="${HEART_T}"><path d="${HEART}" fill="${teal}"/></g>
  </g>`;

const w = await buildWordmark();

const MARK = 64;
const WORD_H = 44;
const ws = WORD_H / w.height;
const wordW = +(w.width * ws).toFixed(2);
const GAP = 18;
const TOTAL_W = +(MARK + GAP + wordW).toFixed(2);
const TOTAL_H = 72;
const markY = (TOTAL_H - MARK) / 2;
const wordY = (TOTAL_H - WORD_H) / 2 + 2;

const write = (rel, body) => {
  const p = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, body);
  console.log("wrote", rel, body.length, "bytes");
};

write(
  "public/brand/logo-mark.svg",
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64" role="img" aria-label="Barber Stucco">
${markGroup(INK, TEAL)}
</svg>
`,
);

const horizontal = (ink, word, heart) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${TOTAL_W} ${TOTAL_H}" width="${TOTAL_W}" height="${TOTAL_H}" role="img" aria-label="Barber Stucco">
${markGroup(ink, heart, ` transform="translate(0 ${markY})"`)}
  <g transform="translate(${MARK + GAP} ${wordY}) scale(${ws.toFixed(5)})" fill="${word}">
    <g transform="${w.transform}"><path d="${w.d}"/></g>
  </g>
</svg>
`;

write("public/brand/logo-horizontal.svg", horizontal(INK, INK, TEAL));
write(
  "public/brand/logo-horizontal-inverse.svg",
  horizontal("#FFFFFF", "#FFFFFF", TEAL_BRIGHT),
);

write(
  "public/brand/favicon.svg",
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">
  <rect width="64" height="64" rx="14" fill="#F7FBFC"/>
  <g transform="translate(32 32) scale(0.84) translate(-32 -32)">
${markGroup(INK, TEAL)}
  </g>
</svg>
`,
);

write(
  "components/brand-paths.ts",
  `// GENERATED by scripts/build-brand.mjs — do not hand-edit.
// Wordmark outlines converted from Great Vibes (SIL Open Font License 1.1).
export const HOUSE_PATH = ${JSON.stringify(HOUSE)};
export const ARCH_PATH = ${JSON.stringify(ARCH)};
export const HEART_PATH = ${JSON.stringify(HEART)};
export const HEART_TRANSFORM = ${JSON.stringify(HEART_T)};
export const WORDMARK_PATH = ${JSON.stringify(w.d)};
export const WORDMARK_TRANSFORM = ${JSON.stringify(w.transform)};
export const WORDMARK_WIDTH = ${w.width};
export const WORDMARK_HEIGHT = ${w.height};
`,
);

console.log(JSON.stringify({ TOTAL_W, TOTAL_H, wordW, ws: +ws.toFixed(5) }));
